version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      #      - KAFKA_BROKER_ID=1001
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    #      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    #      - KAFKA_ADVERTISED_HOST_NAME=localhost
    #      - ALLOW_PLAINTEXT_LISTENER=yes
    #      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    #      - KAFKA_ENABLE_KRAFT=yes
    depends_on:
      - zookeeper
  cmak:
    image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.5:latest
    restart: always
    command:
      - "-Dcmak.zkhosts=zookeeper:2181"
      - "-DbasicAuthentication.enabled=true"
      - "-DbasicAuthentication.username=username"
      - "-DbasicAuthentication.password=password"
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
